-- MySQL Script generated by MySQL Workbench
-- Mon 27 Feb 2017 11:37:09 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quiz` ;

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
USE `quiz` ;

-- -----------------------------------------------------
-- Table `quiz`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz`.`admin` ;

CREATE TABLE IF NOT EXISTS `quiz`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz`.`user` ;

CREATE TABLE IF NOT EXISTS `quiz`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz`.`question` ;

CREATE TABLE IF NOT EXISTS `quiz`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editor` INT NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `solution` VARCHAR(45) NOT NULL,
  `points` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_admin1_idx` (`editor` ASC),
  CONSTRAINT `fk_question_created_by`
    FOREIGN KEY (`editor`)
    REFERENCES `quiz`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz`.`score` ;

CREATE TABLE IF NOT EXISTS `quiz`.`score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `result` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_score_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quiz`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
